"""
Django settings for fuel_route project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
 
BASE_DIR = Path(__file__).resolve().parent.parent
 
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-change-me-in-production-use-env-var"
)
 
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"
 
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")
 
INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "django.contrib.auth",
    "rest_framework",
    "api",
]
 
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
]
 
ROOT_URLCONF = "fuel_route.urls"
 
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
            ],
        },
    },
]
 
WSGI_APPLICATION = "fuel_route.wsgi.application"
 
# No database needed — all data is in-memory from CSV
DATABASES = {}
 
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_TZ = True
 
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
 
# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}
 
# ── Routing / Map API ────────────────────────────────────────────────────────
# OSRM public demo server (free, no key required).
# Swap to your own OSRM instance or another provider via env var.
OSRM_BASE_URL = os.environ.get(
    "OSRM_BASE_URL", "https://router.project-osrm.org"
)
 
# Nominatim geocoding (free, OpenStreetMap)
NOMINATIM_BASE_URL = os.environ.get(
    "NOMINATIM_BASE_URL", "https://nominatim.openstreetmap.org"
)
NOMINATIM_USER_AGENT = os.environ.get(
    "NOMINATIM_USER_AGENT", "FuelRouteAPI/1.0 (contact@example.com)"
)
 
# Vehicle parameters (can be overridden per-request but these are defaults)
DEFAULT_VEHICLE_RANGE_MILES = 500
DEFAULT_MPG = 10
 
# Fuel station data
FUEL_PRICES_CSV = BASE_DIR / "data" / "fuel_prices.csv"
 
# Safety margin: only use 90 % of tank range to avoid running dry
RANGE_SAFETY_FACTOR = 0.90